<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-03 11:44

import django.db.models.deletion
=======
# Generated by Django 5.2.7 on 2025-11-23 19:44

>>>>>>> 5b4842a05845136b4460cd1b3146030f79c267bb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 5b4842a05845136b4460cd1b3146030f79c267bb
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('publication_year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
=======
                ('author', models.CharField(max_length=100)),
>>>>>>> 5b4842a05845136b4460cd1b3146030f79c267bb
            ],
        ),
    ]
